const canvas = document.querySelector('#game');
const ctx = canvas.getContext('2d');
const ui = Object.fromEntries([...document.querySelectorAll('[id]')].map(node => [node.id, node]));
const TAU = Math.PI * 2;
const clamp = (value, min, max) => Number.isFinite(value) ? Math.max(min, Math.min(max, value)) : min;
const distance = (a, b) => Math.hypot(a.x - b.x, a.y - b.y);
export const effectiveDps = (baseDamage, damageMult, attackSpeed, critChance, critMult) => (baseDamage * damageMult) * attackSpeed * (1 + critChance * (critMult - 1));
export const mitigatedDamage = (rawDamage, armor) => rawDamage * (100 / (100 + Math.max(0, armor)));
const relicPool = [
  ['⚡','Chain Lightning','onCrit','Critical hits arc to 3 nearby targets.'], ['☣','Poison Trail','onDash','Dash leaves a toxic zone for 4 seconds.'],
  ['✹','Grave Bloom','onKill','Enemies explode for 40% of max HP.'], ['♥','Blood Harvest','onKill','Kills restore 2% of max vitality.'],
  ['◈','Glass Edge','onHit','Damage +25%, but armor -6.'], ['❄','Cryo Core','onHit','Hits have a 20% chance to freeze.'],
  ['⟡','Ember Sigil','onHit','Hits burn targets for 3 seconds.'], ['↯','Volt Battery','onDash','Dash resets 20% of attack cooldown.'],
  ['✦','Executioner','onCrit','Crit damage +35% against low-health targets.'], ['☄','Razor Orbit','onHit','A blade orbits you and deals contact damage.'],
  ['⌁','Momentum','onDash','Dash grants 30% attack speed for 2 seconds.'], ['♢','Second Wind','onKill','Every 8th kill heals for 12% and grants a shield.']
];
const state = { mode:'playing', wave:1, floor:1, level:1, kills:0, damage:0, bestHit:0, elapsed:0, dps:0, lastDamage:0, shake:0, flash:0, fireCooldown:0, dashCooldown:0, dashTime:0, fireHeld:false, keys:new Set(), mouse:{x:0,y:0,down:false}, relics:[], enemies:[], projectiles:[], particles:[], texts:[], zones:[], obstacles:[], logs:[] };
const player = {x:0,y:0,vx:0,vy:0,r:15,maxHp:100,hp:100,armor:12,damage:18,damageMult:1,attackSpeed:4,crit:.12,critMult:2,invuln:0,speedBoost:0};
const enemyTypes = { swarmer:{hp:34,speed:82,r:12,color:'#e67565',damage:9}, ranger:{hp:58,speed:43,r:13,color:'#e4b766',damage:12}, tank:{hp:190,speed:27,r:20,color:'#c388c0',damage:22} };
const rand = (min,max) => min + Math.random() * (max-min);
function resize(){ const rect=canvas.getBoundingClientRect(); const ratio=Math.min(devicePixelRatio||1,2); canvas.width=rect.width*ratio; canvas.height=rect.height*ratio; ctx.setTransform(ratio,0,0,ratio,0,0); if(!player.x){player.x=rect.width/2;player.y=rect.height/2;} }
function arena(){return {w:canvas.clientWidth,h:canvas.clientHeight};}
function log(message){state.logs.unshift({message,time:state.elapsed});state.logs=state.logs.slice(0,4);ui.combatLog.innerHTML=state.logs.map(item=>`<div class="log-line"><b>${formatTime(item.time)}</b> ${item.message}</div>`).join('');}
function formatTime(seconds){return `${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(Math.floor(seconds%60)).padStart(2,'0')}`;}
function reset(){Object.assign(state,{mode:'playing',wave:1,floor:1,level:1,kills:0,damage:0,bestHit:0,elapsed:0,dps:0,lastDamage:0,shake:0,flash:0,fireCooldown:0,dashCooldown:0,dashTime:0,relics:[],enemies:[],projectiles:[],particles:[],texts:[],zones:[],obstacles:[],logs:[]});Object.assign(player,{x:arena().w/2,y:arena().h/2,vx:0,vy:0,maxHp:100,hp:100,armor:12,damage:18,damageMult:1,attackSpeed:4,crit:.12,critMult:2,invuln:0,speedBoost:0}); hideModal(); createArena(); spawnWave(); log('Run initialized. Ashfall signature detected.'); updateHud();}
function createArena(){const {w,h}=arena();state.obstacles=[];for(let i=0;i<5;i++){let x=rand(80,w-80),y=rand(80,h-80);if(Math.hypot(x-w/2,y-h/2)>130)state.obstacles.push({x,y,r:rand(20,32),kind:i===0?'portal':'column'});}}
function spawnWave(){state.enemies=[];const boss=state.wave%5===0;const count=boss?1:4+state.wave*2;for(let i=0;i<count;i++){const angle=rand(0,TAU),radius=Math.max(arena().w,arena().h)*.5+40;const type=boss?'boss':i%6===0?'tank':i%3===0?'ranger':'swarmer';const base=type==='boss'?{hp:950+state.wave*120,speed:31,r:34,color:'#f06d62',damage:28}:{...enemyTypes[type]};state.enemies.push({x:player.x+Math.cos(angle)*radius,y:player.y+Math.sin(angle)*radius,...base,type, maxHp:base.hp,phase:rand(0,TAU),cooldown:rand(1,3),distance:0,freeze:0,burn:0,hitFlash:0});}ui.bossBar.classList.toggle('active',boss);log(boss?'WARDEN has entered the arena.':'Wave deployed. Hostiles inbound.');}
function movePlayer(dt){let x=(state.keys.has('ArrowRight')||state.keys.has('d')?1:0)-(state.keys.has('ArrowLeft')||state.keys.has('a')?1:0);let y=(state.keys.has('ArrowDown')||state.keys.has('s')?1:0)-(state.keys.has('ArrowUp')||state.keys.has('w')?1:0);const length=Math.hypot(x,y)||1;if(x||y){x/=length;y/=length;player.vx+=(x*260-player.vx)*Math.min(1,dt*10);player.vy+=(y*260-player.vy)*Math.min(1,dt*10);}else{player.vx*=Math.pow(.001,dt);player.vy*=Math.pow(.001,dt);}if(state.dashTime>0){player.vx*=1.02;player.vy*=1.02;}player.x+=player.vx*dt;player.y+=player.vy*dt;const {w,h}=arena();player.x=clamp(player.x,25,w-25);player.y=clamp(player.y,25,h-25);for(const obstacle of state.obstacles){const dx=player.x-obstacle.x,dy=player.y-obstacle.y,d=Math.hypot(dx,dy),min=player.r+obstacle.r;if(d<min){player.x=obstacle.x+dx/d*min;player.y=obstacle.y+dy/d*min;}}}
function dash(){if(state.mode!=='playing'||state.dashCooldown>0)return;let x=player.vx,y=player.vy;const length=Math.hypot(x,y)||1;player.vx=x/length*720;player.vy=y/length*720;player.invuln=.25;state.dashTime=.18;state.dashCooldown=1.2;state.shake=5;for(const relic of state.relics)if(relic[2]==='onDash'&&relic[0]==='☣')state.zones.push({x:player.x,y:player.y,r:42,life:4});log('Dash // i-frames engaged');}
function fire(){if(state.fireCooldown>0||state.mode!=='playing')return;const angle=Math.atan2(state.mouse.y-player.y,state.mouse.x-player.x);state.projectiles.push({x:player.x+Math.cos(angle)*18,y:player.y+Math.sin(angle)*18,vx:Math.cos(angle)*570,vy:Math.sin(angle)*570,life:1.4,damage:player.damage*player.damageMult});state.fireCooldown=1/player.attackSpeed;}
function hitEnemy(enemy,raw,critical=false){const low=enemy.hp<enemy.maxHp*.3;const critMult=critical&&low&&state.relics.some(relic=>relic[0]==='✦')?player.critMult+.35:player.critMult;const damage=mitigatedDamage(raw*(critical?critMult:1),0);enemy.hp-=damage;enemy.hitFlash=.1;state.damage+=damage;state.lastDamage=damage;state.bestHit=Math.max(state.bestHit,damage);state.shake=Math.max(state.shake,critical?6:2);state.flash=.035;state.texts.push({x:enemy.x,y:enemy.y-20,text:`${Math.round(damage)}${critical?' CRIT':''}`,color:critical?'#f4bd62':'#edf6ea',life:1,vy:-28});if(critical&&state.relics.some(relic=>relic[0]==='⚡')){state.enemies.filter(other=>other!==enemy).sort((a,b)=>distance(a,enemy)-distance(b,enemy)).slice(0,3).forEach(other=>hitEnemy(other,damage*.35,false));}if(state.relics.some(relic=>relic[0]==='❄')&&Math.random()<.2)enemy.freeze=2;if(state.relics.some(relic=>relic[0]==='⟡'))enemy.burn=3;}
function updateCombat(dt){state.fireCooldown=Math.max(0,state.fireCooldown-dt);state.dashCooldown=Math.max(0,state.dashCooldown-dt);state.dashTime=Math.max(0,state.dashTime-dt);player.invuln=Math.max(0,player.invuln-dt);player.speedBoost=Math.max(0,player.speedBoost-dt);if(state.mouse.down)fire();for(const projectile of state.projectiles){projectile.x+=projectile.vx*dt;projectile.y+=projectile.vy*dt;projectile.life-=dt;if(projectile.damage>0)for(const enemy of state.enemies){if(enemy.hp>0&&distance(projectile,enemy)<enemy.r+5){const critical=Math.random()<player.crit;hitEnemy(enemy,projectile.damage,critical);projectile.life=0;break;}}}state.projectiles=state.projectiles.filter(item=>item.life>0);for(const enemy of state.enemies){if(enemy.hp<=0)continue;const dx=player.x-enemy.x,dy=player.y-enemy.y,d=Math.hypot(dx,dy)||1;enemy.distance+=enemy.speed*dt;enemy.freeze=Math.max(0,enemy.freeze-dt);enemy.burn=Math.max(0,enemy.burn-dt);if(enemy.burn>0&&Math.random()<dt*2)hitEnemy(enemy,4,false);if(enemy.type==='ranger'){if(d<225){enemy.x-=dx/d*enemy.speed*dt;enemy.y-=dy/d*enemy.speed*dt;}else if(d>290){enemy.x+=dx/d*enemy.speed*dt;enemy.y+=dy/d*enemy.speed*dt;}enemy.cooldown-=dt;if(enemy.cooldown<=0){state.projectiles.push({x:enemy.x,y:enemy.y,vx:dx/d*170,vy:dy/d*170,life:4,damage:-enemy.damage});enemy.cooldown=2.2;}}else if(enemy.type==='boss'){enemy.x+=dx/d*enemy.speed*dt;enemy.y+=dy/d*enemy.speed*dt;enemy.cooldown-=dt;if(enemy.cooldown<=0){for(let i=0;i<12;i++){const a=i*TAU/12+state.elapsed;state.projectiles.push({x:enemy.x,y:enemy.y,vx:Math.cos(a)*145,vy:Math.sin(a)*145,life:4,damage:-enemy.damage*.7});}enemy.cooldown=2;}}else{enemy.x+=dx/d*enemy.speed*(enemy.freeze?0.4:1)*dt;enemy.y+=dy/d*enemy.speed*(enemy.freeze?0.4:1)*dt;}if(d<enemy.r+player.r&&player.invuln<=0){player.hp-=enemy.damage*dt;state.texts.push({x:player.x,y:player.y-20,text:`-${Math.ceil(enemy.damage*dt)}`,color:'#f06d62',life:.4,vy:-10});}if(enemy.hp<=0)killEnemy(enemy);}for(const projectile of state.projectiles){if(projectile.damage<0&&distance(projectile,player)<player.r+5&&player.invuln<=0){player.hp-=mitigatedDamage(-projectile.damage,player.armor);projectile.life=0;state.shake=4;}}for(const zone of state.zones){zone.life-=dt;for(const enemy of state.enemies)if(enemy.hp>0&&distance(zone,enemy)<zone.r)hitEnemy(enemy,8*dt,false);}state.zones=state.zones.filter(zone=>zone.life>0);state.enemies=state.enemies.filter(enemy=>enemy.hp>0);if(state.enemies.length===0&&state.mode==='playing')clearWave();if(player.hp<=0)gameOver();}
function killEnemy(enemy){if(enemy.hp!==0)return;enemy.hp=0;state.kills++;if(state.relics.some(relic=>relic[0]==='♥'))heal(2);if(state.relics.some(relic=>relic[0]==='✹')){for(const other of state.enemies)if(other!==enemy&&distance(other,enemy)<70)hitEnemy(other,enemy.maxHp*.4,false);state.particles.push({x:enemy.x,y:enemy.y,r:5,life:.4,color:'#f4bd62'});}if(state.kills%8===0&&state.relics.some(relic=>relic[0]==='♢'))heal(12);}
function heal(amount){player.hp=clamp(player.hp+amount,0,player.maxHp);state.texts.push({x:player.x,y:player.y-25,text:`+${amount}`,color:'#86e0b1',life:1,vy:-24});}
function clearWave(){state.mode='reward';state.level++;showReward();}
function showReward(){ui.modalKicker.textContent=`WAVE ${String(state.wave).padStart(2,'0')} CLEARED`;ui.modalTitle.textContent='Choose your relic';ui.modalCopy.textContent='One choice. Make it compound.';const available=relicPool.filter(relic=>!state.relics.some(owned=>owned[1]===relic[1])).sort(()=>Math.random()-.5).slice(0,3);ui.choices.innerHTML=available.map((relic,index)=>`<button class="choice" data-choice="${index}"><span class="choice-icon">${relic[0]}</span><h3>${relic[1]}</h3><p>${relic[3]}</p></button>`).join('');available.forEach((relic,index)=>ui.choices.children[index].onclick=()=>{state.relics.push(relic);if(relic[0]==='◈'){player.damageMult+=.25;player.armor=Math.max(0,player.armor-6);}if(relic[0]==='♥')player.maxHp+=20;ui.modal.classList.add('hidden');state.wave++;state.mode='playing';spawnWave();updateHud();});ui.modal.classList.remove('hidden');}
function gameOver(){if(state.mode==='dead')return;state.mode='dead';ui.modalKicker.textContent='RUN TERMINATED';ui.modalTitle.textContent=`${formatTime(state.elapsed)} // ${state.kills} eliminated`;ui.modalCopy.textContent=`Damage dealt ${Math.round(state.damage)} · Best hit ${Math.round(state.bestHit)} · Reached wave ${state.wave}`;ui.choices.innerHTML='';ui.restartButton.classList.remove('hidden');ui.modal.classList.remove('hidden');}
function hideModal(){ui.modal.classList.add('hidden');ui.restartButton.classList.add('hidden');}
function updateHud(){ui.wave.textContent=`${String(state.wave).padStart(2,'0')} / 05`;ui.phaseLabel.textContent=`WAVE ${String(state.wave).padStart(2,'0')}`;ui.timer.textContent=formatTime(state.elapsed);ui.kills.textContent=String(state.kills).padStart(3,'0');ui.damage.textContent=String(Math.round(state.damage)).padStart(4,'0');ui.bestHit.textContent=String(Math.round(state.bestHit)).padStart(3,'0');ui.healthText.textContent=`${Math.ceil(player.hp)} / ${player.maxHp}`;ui.healthBar.style.width=`${clamp(player.hp/player.maxHp*100,0,100)}%`;ui.dashBar.style.width=`${clamp((1-state.dashCooldown/1.2)*100,0,100)}%`;ui.dashText.textContent=state.dashCooldown?'CHARGING':'READY';ui.armor.textContent=player.armor;ui.crit.textContent=`${Math.round(player.crit*100)}%`;ui.dps.textContent=Math.round(state.dps);ui.relicCount.textContent=`${String(state.relics.length).padStart(2,'0')} / 06`;ui.relicList.innerHTML=state.relics.map(relic=>`<div class="relic"><span class="relic-icon">${relic[0]}</span><div><b>${relic[1]}</b><small>${relic[2]}</small></div></div>`).join('');ui.bossHealth.style.width=`${clamp((state.enemies.find(enemy=>enemy.type==='boss')?.hp||0)/(state.enemies.find(enemy=>enemy.type==='boss')?.maxHp||1)*100,0,100)}%`;}
function draw(){const {w,h}=arena();ctx.clearRect(0,0,w,h);ctx.save();if(state.shake>0)ctx.translate(rand(-state.shake,state.shake),rand(-state.shake,state.shake));ctx.fillStyle='#0b1719';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#17302d';ctx.lineWidth=1;for(let x=0;x<w;x+=42){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();}for(let y=0;y<h;y+=42){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();}for(const obstacle of state.obstacles){ctx.strokeStyle=obstacle.kind==='portal'?'#72c8e3':'#35514b';ctx.fillStyle=obstacle.kind==='portal'?'#102d34':'#1b2b2b';ctx.beginPath();ctx.arc(obstacle.x,obstacle.y,obstacle.r,0,TAU);ctx.fill();ctx.stroke();}for(const zone of state.zones){ctx.fillStyle='rgba(134,224,177,.13)';ctx.strokeStyle='#86e0b1';ctx.beginPath();ctx.arc(zone.x,zone.y,zone.r,0,TAU);ctx.fill();ctx.stroke();}for(const projectile of state.projectiles){ctx.fillStyle=projectile.damage<0?'#f06d62':'#f4bd62';ctx.beginPath();ctx.arc(projectile.x,projectile.y,projectile.damage<0?4:3,0,TAU);ctx.fill();}for(const enemy of state.enemies){ctx.save();ctx.translate(enemy.x,enemy.y);ctx.fillStyle=enemy.hitFlash>0?'#fff':enemy.color;ctx.strokeStyle=enemy.type==='boss'?'#f4bd62':'#263b38';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,enemy.r,0,TAU);ctx.fill();ctx.stroke();ctx.fillStyle='#081016';ctx.fillRect(-enemy.r,-enemy.r-10,enemy.r*2,3);ctx.fillStyle='#f06d62';ctx.fillRect(-enemy.r,-enemy.r-10,enemy.r*2*clamp(enemy.hp/enemy.maxHp,0,1),3);ctx.restore();}ctx.save();ctx.translate(player.x,player.y);ctx.rotate(Math.atan2(state.mouse.y-player.y,state.mouse.x-player.x));ctx.fillStyle=player.invuln>0?'#fff':'#86e0b1';ctx.strokeStyle='#dce8df';ctx.beginPath();ctx.moveTo(19,0);ctx.lineTo(-12,-11);ctx.lineTo(-7,0);ctx.lineTo(-12,11);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();for(const text of state.texts){ctx.globalAlpha=clamp(text.life,0,1);ctx.fillStyle=text.color;ctx.font='700 12px Space Mono';ctx.textAlign='center';ctx.fillText(text.text,text.x,text.y);ctx.globalAlpha=1;}ctx.restore();state.shake=Math.max(0,state.shake-0.4);state.flash=Math.max(0,state.flash-.01);if(state.flash){ctx.fillStyle=`rgba(255,255,255,${state.flash})`;ctx.fillRect(0,0,w,h);}}
function update(dt){if(state.mode==='playing'){state.elapsed+=dt;movePlayer(dt);updateCombat(dt);state.dps=state.elapsed?state.damage/state.elapsed:0;}for(const text of state.texts){text.y+=text.vy*dt;text.life-=dt;}state.texts=state.texts.filter(text=>text.life>0);for(const enemy of state.enemies)enemy.hitFlash=Math.max(0,enemy.hitFlash-dt);updateHud();draw();requestAnimationFrame(loop);}
let previous=performance.now();function loop(now){const dt=Math.min(.033,(now-previous)/1000);previous=now;update(dt);}window.addEventListener('resize',resize);window.addEventListener('keydown',event=>{state.keys.add(event.key);if(event.code==='Space'){event.preventDefault();dash();}});window.addEventListener('keyup',event=>state.keys.delete(event.key));canvas.addEventListener('pointermove',event=>{const rect=canvas.getBoundingClientRect();state.mouse.x=event.clientX-rect.left;state.mouse.y=event.clientY-rect.top;});canvas.addEventListener('pointerdown',()=>state.mouse.down=true);window.addEventListener('pointerup',()=>state.mouse.down=false);ui.newRunButton.onclick=reset;ui.restartButton.onclick=reset;resize();reset();requestAnimationFrame(loop);
